### ISSUE TITLE
Plugin could not be started

### ISSUE THREAD

**Issue by l13rb4git** [BadCoder1337/bd-imgurstickers#1]
Trying to load the plugin on betterdiscord make this error message appear. 
![image](https://user-images.githubusercontent.com/34998720/115391776-3af22680-a1b6-11eb-8ab6-1edeba1b455e.png)
Sadly, the plugin is not working.

**Comment by BadCoder1337** [comment]
My plugin was left in 2018. BetterDiscord got a major update, Discord emote menu got a major redesign. 

BD API is weird, have lack of docs. I haven't touched it for a couple of years.
I realised that Discord client mods don't offer anything except useless gimmicks. 

Thank you for attention, but i won't update it. Emojis without text looks bigger than in 2018. Buy Nitro.
